### PR TITLE
Ran black, updated to pylint 2.x

### PR DESCRIPTION
**Pull request by evaherrada**
#8. I removed range and zip being self-assigned. I also added disables for import-outside-toplevel since that seems like the way we decided on handling that for other libraries. 

@brentru It'd be awesome if you could test this. Thanks!

### CODE REVIEW

**Review by kattni — APPROVED** [review]
The rest is approved. @brentru You can proceed with merging following testing.

**Comment by brentru** [comment]
Hitting an error in Simpletst, checking current `master` to see if that's affected. It may be a 5.0 issue.
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Generating keypair...
Encrypting message...
Traceback (most recent call last):
  File "code.py", line 16, in <module>
  File "/lib/adafruit_rsa/pkcs1.py", line 173, in encrypt
  File "/lib/adafruit_rsa/transform.py", line 181, in int2bytes
AssertionError: Number must be an unsigned integer, not a float.
```

**Comment by brentru** [comment]
Seems to be an issue in `master`, however it got further than this PR. Going to load 4.x libs and deps. on my board to check.

```
**Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Generating keypair...
Encrypting message...
Decrypting message...
Traceback (most recent call last):
  File "code.py", line 20, in <module>
  File "/lib/adafruit_rsa/pkcs1.py", line 232, in decrypt
  File "/lib/adafruit_rsa/transform.py", line 177, in int2bytes
AssertionError: Number must be an unsigned integer, not a float.**
```

**Comment by brentru** [comment]
@kattni  This error is appearing on 4.x and 5.x builds, not sure why, I'd need to do some digging. I can open an issue and investigate. It's not related to Dylans PR. 

Would you want to merge this in and not release yet, or wait for the patch and merge that first? I'll base the patch branch off this PR if you would like.

4.x
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Generating keypair...
Encrypting message...
Traceback (most recent call last):
  File "code.py", line 16, in <module>
  File "/lib/adafruit_rsa/pkcs1.py", line 173, in encrypt
  File "/lib/adafruit_rsa/transform.py", line 177, in int2bytes
AssertionError: Number must be an unsigned integer, not a float.```

**Comment by kattni** [comment]
@brentru Let's merge and then you can move forward with sorting it out with this already included.

**Comment by brentru** [comment]
@kattni  sounds good to me, LGTM aside from this.

**Pull request merged**
