### PR TITLE
Add pyasn1 as dependency

### PR DESCRIPTION
**Pull request by tekktrik**
One of the changes from #22 that is needed a little more urgently, given that it is an unmarked and unincluded dependency for this library.  Figured it was better to separate it out so it can be applied faster.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
I'm not sure that I understand why this is a required dependency. Did you do some testing and run into a need for it? On a Feather RP2040 I am able to run the simpletest for this library as is without `pyasn1`

Here is output from successful run and lack of pyasn1
```
Adafruit CircuitPython 7.2.3 on 2022-03-16; Adafruit Feather RP2040 with rp2040
>>> 
>>> import adafruit_rsa
>>> import rsa_simpletest
Generating keypair...
Encrypting message...
Decrypting message...
Decrypted Message:  hello blinka
>>> import pyasn1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'pyasn1'
>>> 
```
Is this needed only in specific use cases or something like that?

**Comment by FoamyGuy** [comment]
The other two scripts in examples, `rsa_tests.py` and `rsa_sign_verify.py` also seem to execute successfully on the Feather RP2040 without `pyasn1`

**Comment by tekktrik** [comment]
Ah, well glad the simpletest works.  My reasoning is that `key.py` and `asn1.py` have functionalities relying on `pyasn1` (which is only available on Blinka or pooooossibly using the library as is from the GitHub repo if it doesn't have its own dependencies).  Since I'm not sure about the latter, this PR at least addresses the first by adding it as a dependency.  But I was concerned about whether is was working as is so that's good!

**Comment by FoamyGuy** [comment]
I'm not sure I understand the use case for this library on Blinka if there are specific parts that only work in that environment. In a CPython environment with Blinka there is the built-in module `rsa` that could be used instead of this library if I understand correctly. 

My understanding was that this library is used only on microcontrollers normally since we don't have the core module `rsa` this implements a subset of it.

**Comment by tekktrik** [comment]
No that's a very good point.  I guess then looking at the pyasn1 library maybe it should at least be made clearer in the README that certain functionality depends on the `pyasn1` library.  I can remove the commits to `setup.py` and `requirements.txt` in that case, and rephrase the changes to the README.

**Comment by tekktrik** [comment]
Would a `try`/`except` for wherever those are imported to catch the import error and transforming it be a good idea?  Essentially:

```python
try:
    import pyasn1
except ImportError as err:
    raise ImportError("This functionality requires the pyasn1 library") from err
```

**Comment by FoamyGuy** [comment]
> Would a `try`/`except` for wherever those are imported to catch the import error and transforming it be a good idea? Essentially:

I do like this idea. This way anyone who is trying to use that functionality will get a helpful error message telling them what is wrong. But anyone not using the functionality will not end up having it get installed by pip automatically.

**Comment by tekktrik** [comment]
Sounds good, in that case just be aware I reverted the changes here and force pushed new changes onto the branch, based on the discussion here!

**Comment by tekktrik** [comment]
Wanted to keep a cleaner history :D

**Review by askpatrickw — APPROVED** [review]
This change makes sense, but I did not test.

**Review by FoamyGuy — APPROVED** [review]
Looks good to me. Tested all 3 scripts in the examples folder successfully on PyPortal Titano

**Pull request merged**
