### PR TITLE
Prelim minimization work & fix bugs

### PR DESCRIPTION
**Pull request by geudrik**
Work in progress. This resolves the import depth issues reported [here](https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/issues/19)

Note that [this PR](https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/pull/20) is also likely necessary on some boards, as NTP can be a PITA (eg: on the Feather S2)

### CODE REVIEW

**Comment by geudrik** [comment]
I've marked this as a WIP only because so far I've tested far enough to verify that the depth issues are resolved. I haven't actually tested functionality yet

**Comment by brentru** [comment]
@geudrik  Please tag me when you're ready for a review

**Comment by FoamyGuy** [comment]
checking in with @geudrik, are you still working on this PR?

**Comment by geudrik** [comment]
I unfortunately haven't touched this work in a few months (I moved). I got stuck buried in one of the other three MR's related to this though - this was a deep rabbit hole, and I don't know enough about how the MQTT protocol works to actually resolve it.

All of this work was together with https://github.com/adafruit/Adafruit_CircuitPython_GC_IOT_Core/pull/20 and https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/93 to get Pub/Sub plugged in and working on my S2 (see [here](https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/issues/93#issuecomment-942769108) for the final "here's where I got stuck")

**Comment by FoamyGuy** [comment]
@geudrik it's all a bit over my head honestly. Don't have much experience with MQTT. 

Do any of these PRs provide functionality or improvements that stand on their own? or are all really a package deal type of thing? 

For now I think maybe we can close any that are stuck for the time being? If we do, definitely feel free to re-open or create new PRs if you do end up getting back into it and unblocked.

**Comment by geudrik** [comment]
Feel free to close for now. Most should stand on their own, though I can't speak to their current state or how else they may interact with other adafruit libs. It was a compound issue - stack depth issues was the first piece of cleanup, then mqtt/pubsub since that doesn't work at all currently.

**Pull request closed without merging**
