### PR TITLE
Improve documentation

### LINKED ISSUE #19: Missing Type Annotations
There are missing type annotations for some functions in this library.

The `typing` module does not exist on CircuitPython devices so the import needs to be wrapped in try/except to catch the error for missing import. There is an example of how that is done here:

```python
try:
    from typing import List, Tuple
except ImportError:
    pass
```

Once imported the typing annotations for the argument type(s), and return type(s) can be added to the function signature. Here is an example of a function that has had this done already:

```python
def wrap_text_to_pixels(
    string: str, max_width: int, font=None, indent0: str = "", indent1: str = ""
) -> List[str]:
```
If you are new to Git or Github we have a guide about contributing to our projects here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

There is also a guide that covers our CI utilities and how to run them locally to ensure they will pass in Github Actions here: https://learn.adafruit.com/creating-and-sharing-a-circuitpython-library/check-your-code In particular the pages: `Sharing docs on ReadTheDocs` and `Check your code with pre-commit` contain the tools to install and commands to run locally to run the checks.

If you are attempting to resolve this issue and need help, you can post a comment on this issue and tag both @foamyguy and @kattni or reach out to us on Discord: https://adafru.it/discord in the `#circuitpython-dev` channel.

The following locations are reported by mypy to be missing type annotations:

- [ ] adafruit_rsa/machine_size.py:30
- [ ] adafruit_rsa/common.py:14
- [ ] adafruit_rsa/common.py:27
- [ ] adafruit_rsa/common.py:36
- [ ] adafruit_rsa/common.py:66
- [ ] adafruit_rsa/common.py:91
- [ ] adafruit_rsa/common.py:115
- [ ] adafruit_rsa/common.py:139
- [ ] adafruit_rsa/common.py:156
- [ ] adafruit_rsa/_compat.py:34
- [ ] adafruit_rsa/_compat.py:43
- [ ] adafruit_rsa/_compat.py:55
- [ ] adafruit_rsa/_compat.py:67
- [ ] adafruit_rsa/_compat.py:83
- [ ] adafruit_rsa/_compat.py:101
- [ ] adafruit_rsa/pem.py:16
- [ ] adafruit_rsa/pem.py:30
- [ ] adafruit_rsa/pem.py:96
- [ ] adafruit_rsa/core.py:19
- [ ] adafruit_rsa/core.py:38
- [ ] adafruit_rsa/core.py:46
- [ ] adafruit_rsa/core.py:64
- [ ] adafruit_rsa/transform.py:23
- [ ] adafruit_rsa/transform.py:38
- [ ] adafruit_rsa/transform.py:106
- [ ] adafruit_rsa/transform.py:131
- [ ] adafruit_rsa/randnum.py:19
- [ ] adafruit_rsa/randnum.py:40
- [ ] adafruit_rsa/randnum.py:53
- [ ] adafruit_rsa/randnum.py:66
- [ ] adafruit_rsa/pkcs1.py:58
- [ ] adafruit_rsa/pkcs1.py:103
- [ ] adafruit_rsa/pkcs1.py:136
- [ ] adafruit_rsa/pkcs1.py:167
- [ ] adafruit_rsa/pkcs1.py:232
- [ ] adafruit_rsa/pkcs1.py:266
- [ ] adafruit_rsa/pkcs1.py:288
- [ ] adafruit_rsa/pkcs1.py:323
- [ ] adafruit_rsa/pkcs1.py:342
- [ ] adafruit_rsa/pkcs1.py:363
- [ ] adafruit_rsa/pkcs1.py:391
- [ ] adafruit_rsa/prime.py:21
- [ ] adafruit_rsa/prime.py:33
- [ ] adafruit_rsa/prime.py:59
- [ ] adafruit_rsa/prime.py:112
- [ ] adafruit_rsa/prime.py:123
- [ ] adafruit_rsa/prime.py:149
- [ ] adafruit_rsa/prime.py:177
- [ ] adafruit_rsa/key.py:48
- [ ] adafruit_rsa/key.py:53
- [ ] adafruit_rsa/key.py:65
- [ ] adafruit_rsa/key.py:91
- [ ] adafruit_rsa/key.py:116
- [ ] adafruit_rsa/key.py:127
- [ ] adafruit_rsa/key.py:144
- [ ] adafruit_rsa/key.py:161
- [ ] adafruit_rsa/key.py:203
- [ ] adafruit_rsa/key.py:213
- [ ] adafruit_rsa/key.py:217
- [ ] adafruit_rsa/key.py:226
- [ ] adafruit_rsa/key.py:233
- [ ] adafruit_rsa/key.py:277
- [ ] adafruit_rsa/key.py:302
- [ ] adafruit_rsa/key.py:321
- [ ] adafruit_rsa/key.py:370
- [ ] adafruit_rsa/key.py:381
- [ ] adafruit_rsa/key.py:397
- [ ] adafruit_rsa/key.py:401
- [ ] adafruit_rsa/key.py:419
- [ ] adafruit_rsa/key.py:427
- [ ] adafruit_rsa/key.py:443
- [ ] adafruit_rsa/key.py:459
- [ ] adafruit_rsa/key.py:557
- [ ] adafruit_rsa/key.py:583
- [ ] adafruit_rsa/key.py:628
- [ ] adafruit_rsa/key.py:661
- [ ] adafruit_rsa/key.py:696
- [ ] adafruit_rsa/key.py:709
- [ ] adafruit_rsa/key.py:737

### PR DESCRIPTION
**Pull request by tekktrik**
This one was a doozy!  I feel like there were a lot of places where I used `bytes` and `circuitpython_typing.ReadableBuffer` would have been fine, but the intention was really to use `bytes` so I did that.

Also added some documentation updates related to type annotation, but this library would benefit from more thorough documentation of parameters.

Resolves #19 

UPDATE
------------

This PR further improves documentation by cleaning up a lot of the module, class, and method docstrings, then adding the missing modules to `api.rst` so said documentation will be displayed.

Also, this library seemed to have an undocumented dependency on `pyasn1` so I added it to `setup.py` and `requirements.txt`.

### CODE REVIEW

**Comment by tekktrik** [comment]
Scope of the PR has increased, so updated initial comment.

**Comment by tekktrik** [comment]
Going to separate out the changes from #25 from this PR, draft for now

**Comment by tekktrik** [comment]
Ew, ugly git commit history!  Will resubmit.

**Comment by kattni** [comment]
@tekktrik We don't mind lengthy git histories. You don't need to close PRs and resubmit them solely for that reason. Please feel free to stick with PRs regardless of the git history. Thanks for all you've been doing!

**Pull request closed without merging**
